mdx/entry/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('list', views.list, name='list'),
    path('start', views.start, name='start'),
    path('<int:q_id>/', views.detail, name='detail'),
    path('<int:q_id>/results/', views.results, name='results'),
    path('<int:q_id>/enter/', views.enter, name='enter'),
    path('success', views.save_response, name='save_response'),
    path('continue/<int:survey_id>', views.survey, name='survey'),
    path('explain', views.explain, name='explain'),
   
]

mdx/mdx/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('entry/', include('entry.urls')),
    path('admin/', admin.site.urls),
    path('', include('entry.urls'))
]

mdx/entry/models.py
from django.db import models


RESPONSE_CHOICES = (
    ('no','No'),
    ('yes', 'Yes'),
)

class Question(models.Model):
    readonly_fields=('id')
    text = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    is_noise = models.BooleanField(default=True)

    def __str__(self):
        return str(self.text)

    def get_choices(self):
        return self.choice_set.all()

class Choice(models.Model):
    readonly_fields=('id')
    text = models.CharField(max_length=200)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"question: {self.question.text}, choice: {self.text}"


class Survey(models.Model):
    epsilon = models.FloatField(default=4.0)
    accuracy = models.IntegerField(default=80)
    noise = models.IntegerField(default=20)
    created = models.DateTimeField(auto_now_add=True)    
    def __str__(self):
        return str(self.id)

class Response(models.Model):
    readonly_fields=('id')
    text = models.CharField(max_length=6, choices=RESPONSE_CHOICES, default='yes')
    created = models.DateTimeField(auto_now_add=True)
    survey = models.ForeignKey(Survey,related_name="responses", on_delete=models.CASCADE)
    def __str__(self):
        return f"response: {self.id}"




   

mdx/entry/forms.py
from django.forms import ModelForm
from .models import Survey, Response

# Create the form class.
class SurveyForm(ModelForm):
    class Meta:
        model = Survey
        fields = '__all__'

class ResponseForm(ModelForm):
    class Meta:
        model = Response
        fields = '__all__'

mdx/entry/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from django.http import Http404
from .forms import *
import requests
import random
import json

from .models import *
# Create your views here.


def index(request):
    return render(request, 'entry/index.html')

def explain(request):
    return render(request, 'entry/explain.html')

# the sets up a survey, the user sets the desired accuracy level required for the survey
# the related noise, epsilon values are computed alongside
def start(request):
    form = SurveyForm()
    if request.method == 'POST':
        form = SurveyForm(request.POST)
        if form.is_valid():
            instance = form.save()
            survey_record = Survey.objects.get(id = instance.id)
            survey_record.noise = (100-survey_record.accuracy)
            if survey_record.noise <= 0:
                survey_record.noise = 1
            if survey_record.accuracy > 100:
                survey_record.accuracy = 100

            survey_record.epsilon = round(survey_record.accuracy/survey_record.noise, 2)
            survey_record.save()
            return survey(request, survey_id = instance.id)
    context = {'form': form}
    return render(request, 'entry/start.html', context)

def survey(request, survey_id):
    #retreive details of survey
    survey_record = Survey.objects.get(id = survey_id)
    
    #decide if user should get get noise question or not
    accuracy_needed = accuracyornoise(survey_record.accuracy)
    question_record = Question.objects.get(is_noise = accuracy_needed.get("result"))
    accuracy_needed['survey_id'] = survey_id
    return detail(request, question_record.id, accuracy_needed)


# this function is like a virtual coin flip, 
# it decides if the question should be one that gives a noise response or an accurate one by comparing 
# the accuracy value needed in the survey with a random number
def accuracyornoise(accuracy):

    # we generate a random value using a public API that shows numbers from atmospheric noise
    resource_url = 'https://www.random.org/integers/'
    params = {"num": 1, "min": 1, "max":100, "col":1, "base":10,
             "format":"plain", "rnd": "new"}
    request_for_naturalrandom = requests.get(resource_url, params)
   
    if request_for_naturalrandom.status_code == 200:
        generated_random = int(request_for_naturalrandom.text)
    else:
        # fall back in case Randomizing API is not available
        generated_random = random.randint(0, 100)

    # Decide if the question shown should be a noise question or real one
    if accuracy <= generated_random:
        add_noise = True
    else:
        add_noise = False

    noise = (100-accuracy)

    if noise <= 0:
        noise = 1
    if accuracy > 100:
        accuracy = 100
    
    # from differential privacy formula
    epsilon = round(accuracy/noise, 2)

    # return computated values to the application to display the question
    return {'accuracy': accuracy, 'noise': noise, 'epsilon': epsilon, 
            'randomized_number': generated_random, 'result': add_noise}



def detail(request, q_id, accuracy):

    form = ResponseForm(initial={'survey': accuracy['survey_id']})

    try:
        question = Question.objects.get(pk=q_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'entry/detail.html', {'form': form, 'question': question, 'accuracy': accuracy})

def save_response(request):
    if request.method == 'POST':
        form = ResponseForm(request.POST)
    if form.is_valid():
        instance = form.save()

    survey_id = form.cleaned_data['survey']
    log = json_report(survey_id.id)
    
    return render(request, 'entry/response_complete.html', {'survey_id':form.cleaned_data['survey'], 'response_id':instance.id, 'log':log})

def json_report(survey_id):
    survey = Survey.objects.get(pk=survey_id)
    yes_count = Response.objects.filter(survey=survey.id, text = 'yes').count()
    no_count = Response.objects.filter(survey=survey.id, text = 'no').count()
    responses = (yes_count+no_count)
    log = {"id":survey.id, "accuracy":survey.accuracy, "noise": survey.noise, "epsilon":survey.epsilon, "yes": yes_count, "no":no_count, "total_responses":responses}
    return json.dumps(log)

def results(request, q_id):
    response = "Result of Question %s."
    return HttpResponse(response % q_id)

def enter(request, q_id):
    return HttpResponse("Answering: %s." % q_id)

def list(request):
    latest_question_list = Question.objects.order_by('-created')[:5]
    template = loader.get_template('entry/index.html')
    output = ', '.join([q.text for q in latest_question_list])
    #return HttpResponse(output)
    return render(request, 'entry/list.html', {'question': output})

mdx/entry/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css" integrity="sha512-8bHTC73gkZ7rZ7vpqUQThUDhqcNFyYi2xgDgPDHc+GXVGHXq+xPjynxIopALmOPqzo9JZj0k6OqqewdGO3EsrQ==" crossorigin="anonymous" referrerpolicy="no-referrer" /><script
  src="https://code.jquery.com/jquery-3.1.1.min.js"
  integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
  crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js" integrity="sha512-dqw6X88iGgZlTsONxZK9ePmJEFrmHwpuMrsUChjAw1mRUhUITE5QU9pkcSox+ynfLhL15Sv2al5A0LVyDCmtUw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://tyleryasaka.github.io/semantic-ui-range/range.js"></script>


<div class="ui fixed inverted menu">
    <div class="ui container">
      <a href="/entry" class="header item">
        <img class="logo" src="https://www.mdx.ac.uk/__data/assets/image/0017/141902/MU_Malta_white-text-small.png" style="width:auto; height: 2.5em;">
      </a>
      <a href={% url 'explain' %}  class="item">How it works</a>
      <a href="/entry/start" class="item">Start</a>

      
    </div>
  </div>
    <title>MdxPrivacy™ | A local differential privacy based data collection app {% block title %} {% endblock %}</title>
</head>

<h3 class="ui center aligned header"></h3>

<body style="margin: 10em 10em 0 0;height: 600px;">

    <div class="ui three column doubling stackable grid">
        <div class="column">
        </div>
        <div class="column">
          
            {% block content %}

            {% endblock %}
        </div>
        <div class="column">
        </div>
        
    </div>






      <div>

        
        <div id="footer" class="ui center aligned container">
            <p style="color:grey;padding:10em;" >Built by <a style="color:grey;cursor: pointer;" target="_blank" href="https://allentom.me">Allen Tom</a>, as partial fulfillment of the requirements for the MSc degree in BISM at Middlesex University, Malta</p>
        </div>
    
    </div>

</body>


</html>

mdx/entry/templates/entry/detail.html
{% extends "base.html" %}

{% block content %}

<div class="ui cards">
    <div class="card">
      <div class="content">
        <div class="header">{{ question.text }}</div>
        <div class="meta">Select your option</div>
        <div class="description">
            <div class="ui form">                    
                    <form action = {% url 'save_response' %} method="post" class="ui form">
                        {% csrf_token %}
            
                        <!--
                        <div class="field">
                            <label>Select</label>
                            {{form.text}}
                        </div>
                        !-->
                        <div class="ui form">
                            <div class="inline fields">
                              <div class="field">
                                <div class="ui radio checkbox">
                                  <input type="radio" value="yes" name="text" checked="checked">
                                  <label>Yes</label>
                                </div>
                              </div>
                              <div class="field">
                                <div class="ui radio checkbox">
                                  <input type="radio" value="no" name="text">
                                  <label>No</label>
                                </div>
                              </div>
                            </div>
                        </div>

            
                        <div class="field" style="display:none;">
                            <label>Survey</label>
                            {{form.survey}}
                        </div>
                       
                        <button class="ui right labeled icon teal button"type="submit" value="Submit">
                        <i class="right check icon"></i>
                            Done!
                         </button>
                    </form>
             </div>


        </div>
      </div>
    </div>
</div>

<div class="ui two column stackable grid">
    <div class="column">
        
    </div>
    <div class="column">
        <div class="ui statistics">
            <div class="statistic">
              <div class="value">
                {{ accuracy.accuracy }}<span style="font-size: 40%;">%</span>
              </div>
              <div class="label">
                Accuracy
              </div>
            </div>
            <div class="statistic">
              <div class="value">
                {{ accuracy.noise }}<span style="font-size: 40%;">%</span>
              </div>
              <div class="label">
                Noise
              </div>
            </div>

          </div>
    
    </div>
  </div>

  <div class="ui two column stackable grid">
    <div class="column">
        <!-- Slider goes here -->
    </div>
    <div class="column" style="color:#a4a4a5;">
    <p>Current epsilon (ε) is {{ accuracy.epsilon }} </p> <br>

    Differential privacy describes ε as the privacy budget value. Lower values of ε leads to better privacy of results. It represents the proportion of accurate responses to added noise entries. For example a ε of 3 has respondents answer accurately 75% of the time while 25% of the responses are noise entries added to protect privacy of the dataset (Kenny et al., 2021). 
    </div>
  </div>


{% endblock content %}

mdx/entry/templates/entry/explain.html
{% extends "base.html" %}


{% block content %}
<div class="ui segment">

    <p style="color:#808080; margin:1em;">
        <b>How is the survey secure?</b>
        <br>
        
        The data collection is protected by a layer of randomness. We would never know exactly who answered what. Prior to starting the survey, we selected an accuracy value. We asked a sensitive question in the survey, there is a non-sensitive question included as well. The responses to both are either Yes/No. The accuracy value determines what proportion of users get the sensitive question. We only record the response and do not record which question you answered.
        <br> <br>

        In order to make the noise truly local, the privacy value is compared against a natural random number that is generated individually for each user from atmospheric noise (through the random.org API).  
        
        <br>        <br>
        <b>What about the survey result?</b><br>

        
        Based on final summarized statistic, the noise could be computed alongside the number of resonses using the initial accuracy level.  This statistic shows what proportion of users  might have answered Yes to the sensitive question. This means we can derive insights from the total dataset without breaching the privacy of a single individual.
        <br>        <br><br>

        <i>Wang, T., Zhao, J., Hu, Z., Yang, X., Ren, X. and Lam, K.Y., 2021. Local Differential Privacy for data collection and analysis. Neurocomputing, 426, pp.114-133.<i>
        <br><br>
        <i>Tanyer, S.G., 2014, September. True random number generation of very high goodness-of-fit and randomness qualities. In 2014 International Conference on Mathematics and Computers in Sciences and in Industry (pp. 213-215). IEEE.</i>
        </p>
</div>

{% endblock content %}

mdx/entry/templates/entry/index.html
{% extends "base.html" %}


{% block content %}
<h1><img src="https://gitlab.com/allentom/privacyanywhere/-/raw/main/mdx/mdx_logo.png" height="50px" style="margin-right:0.25em;">MdxPrivacy™</h1>
<div class="ui divider"></div>
<h2 style="color:#c4c4c4;margin-top:0.75em;">A data collection application built using local differential privacy</h2>


{% endblock content %}

mdx/entry/templates/entry/list.html
{% extends "base.html" %}

<h1>List of Entries</h1>


{% block content %}

    {% if latest_question_list %}
    
        <ul>
        {% for question in latest_question_list %}
            <li><a href="/entry/{{ question.id }}/">{{ question.text }}</a></li>
        {% endfor %}
        </ul>

        {% else %}
        <p>No Questions are available.</p>

    {% endif %}

{% endblock content %}

mdx/entry/templates/entry/response_complete.html
{% extends "base.html" %}

{% block content %}

<script type="text/javascript">

    jQuery(function() {
        jQuery('#show_log').on('click', function(){
            jQuery('#log_section').removeClass('hidden');
        });    
    });
    
</script>
<div class="ui cards">
    <div class="card">
      <div class="content">
        <div class="header">
            Thank you! 
        </div>
        <div class="meta">
            Your information was securely processed using local differential privacy. 
        </div>
        <div class="description">

        </div>
      </div>
      <div class="extra content">
        <div class="ui two buttons">
            <a class="ui basic green button" href='continue/{{survey_id}}'>New Entry</a>
            <a class="ui basic blue button" href='start'>New Survey</a>
        </div>
      </div>
    </div>
</div> 

</br>

<div class="ui basic segment">
<a style="color:#a5a5a5;margin:2em;" id="show_log" href="#">
    Click to view Survey log</a>
</div>
<br>

<div style="margin-top:3em;" id="log_section" class="ui info message transition hidden">
    <div class="header">
    Done!
    </div>
    <br>
    {{log}}
  </div>

{% endblock content %}

mdx/entry/templates/entry/start.html
{% extends "base.html" %}

{% block content %}

<div class="ui cards">
    <div class="card">
      <div class="content">
        <div class="header">Design your survey</div>
        <div class="meta">How private should the entries be? <br><span style="font-size:95%;">higher accuracy means lower privacy</span></div><br>
        <div class="description">
        <form action="start" method="post" class="ui big form">
            {% csrf_token %}

            <div class="field" style="display:none;">
                <label>Epsilon (ε)</label>
                {{form.epsilon}}
            </div>

            <div class="field" style="display:none;">
                <label>Noise</label>
                {{form.noise}}
            </div>

            <!--
            <div class="field">
                <label>Accuracy</label>
                {{form.accuracy}}
            </div>
            !-->

            <div class="seven wide field">
                <label>Accuracy %</label>
                <input type="number" name="accuracy" value="80" max="100" min="0" placeholder="" required="" id="id_accuracy">
            </div>
           
            <button class="ui right labeled icon teal button"type="submit" value="Submit">
            <i class="right arrow icon"></i>
                Start
             </button>
        </form>
        </div>
      </div>
    </div>
</div>


{% endblock content %}